### ISSUE TITLE
底部状态栏好像有问题

### ISSUE THREAD

**Issue by Timelesseternity** [royc01/salt#10]
最开始进入思源的时候，在底部状态栏会显示字数、词数。但是后来这个就无法显示了，如下图所示
![image](https://user-images.githubusercontent.com/108171881/195019598-fe21deab-a8b4-4724-9b36-629f37cbe1c1.png)

**Comment by royc01** [comment]
这个问题在下个版本修复，大概明天吧

**Comment by Timelesseternity** [comment]
辛苦作者了
