### ISSUE TITLE
【建议】建议让被钉住的标签页显示完整名称

### ISSUE THREAD

**Issue by ghost** [royc01/salt#2]
目前salt和notion theme主题中，如果标签页被钉住，只能显示每个标签页的第一个字，如下图：

![image](https://user-images.githubusercontent.com/53759402/170698908-c6004caf-60de-4a15-8278-cc4b4b1a5028.png)

建议这点和默认主题保持一致，能够显示出完整的名称。

**Comment by royc01** [comment]
感谢反馈，这是保持钉住页签的一致性特性，或者看看有没有更多反馈

**Comment by royc01** [comment]
已修改
